---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/english/author
  label: Author (en)
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: exampleSite/content/french/author
  label: Author (fr)
  create: all
  match: "**/*"
  templates:
  - author
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/english/post
  label: Post (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/french/post
  label: Post (fr)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Portfolio
- type: directory
  path: exampleSite/content/english/portfolio
  label: Portfolio (en)
  create: all
  match: "**/*"
  templates:
  - portfolio
- type: directory
  path: exampleSite/content/french/portfolio
  label: Portfolio (fr)
  create: all
  match: "**/*"
  templates:
  - portfolio
- type: heading
  label: Others Page
- type: document
  path: exampleSite/content/english/about/_index.md
  label: About (en)
- type: document
  path: exampleSite/content/french/about/_index.md
  label: About (fr)
- type: document
  path: exampleSite/content/english/contact/_index.md
  label: Contact (en)
- type: document
  path: exampleSite/content/french/contact/_index.md
  label: Contact (fr)
- type: document
  path: exampleSite/content/english/privacy-policy/_index.md
  label: Privacy (en)
- type: document
  path: exampleSite/content/french/privacy-policy/_index.md
  label: Privacy (fr)
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/english
  label: All page (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/french
  label: All Page (fr)
  create: all
  match: "**/*"
- type: heading
  label: Translation
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
